### PR TITLE
Send slack reports after worker task

### PR DESCRIPTION
**Pull request by yum25**
Sends a daily slack report after worker runs. 
Only reports data on the current day and day before. 

Currently thinking about:
- Investigating if it's possible to ping the channel when the amount of images without alt text reaches a numerical threshold
- Reorganizing worker code to increase positive vibes
- Maybe only send data from yesterday, and move cron trigger closer to morning/midday

### CODE REVIEW

**Comment by erxclau** [comment]
This is really exciting! I think its really nice to have this as an example for other use cases. I've personally also been thinking about Slack logging in the context of Games (https://github.com/michigandaily/games/issues/88, https://github.com/michigandaily/games/issues/94) and the mobile app (both on the device and for notifications).

> Maybe only send data from yesterday, and move cron trigger closer to morning/midday

I think this would be a good idea. To that end, one approach could be to ping the WordPress endpoint hourly (instead of just once a day) to capture posts between 8PM and 12AM (which is arguably when most stories are published). And you can also have multiple cron triggers that can be [targeted](https://developers.cloudflare.com/workers/runtime-apis/handlers/scheduled/#syntax) at different actions (ping endpoint or send Slack report).

> Reorganizing worker code to increase positive vibes

Two workers? Maybe not necessary but a possible approach.

> Investigating if it's possible to ping the channel when the amount of images without alt text reaches a numerical threshold

Have you come across this: <https://api.slack.com/reference/surfaces/formatting#special-mentions>? I'm guessing the `<!channel>` is the proper syntax.

**Comment by erxclau** [comment]
Looks like there is also date formatting: <https://api.slack.com/reference/surfaces/formatting#date-formatting>

**Comment by yum25** [comment]
Note:

Attempted to use date formatting with the link, but for some reason slack escapes the ampersands specifically with the date optional link. Slack does not do this with a normal link. Sad.

**Review by erxclau — APPROVED** [review]
stunning

**Pull request merged**
